# Generated by Django 6.0.3 on 2026-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, verbose_name='NIT/RUT')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('moneda', models.CharField(default='$', max_length=10)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
        migrations.CreateModel(
            name='RegistroRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='backups/')),
                ('exitoso', models.BooleanField(default=True)),
                ('tamano_mb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Respaldo',
                'verbose_name_plural': 'Registros de Respaldos',
            },
        ),
    ]