# Generated by Django 6.0.3 on 2026-04-21 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.IntegerField(default=2024)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_nomina', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagada', 'Pagada')], default='borrador', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('egresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('neto_recibir', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rrhh.nomina')),
            ],
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
        ),
    ]
