# Generated by Django 6.0.3 on 2026-04-21 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_swift', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesoreria.banco')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='pendiente', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='pendiente', max_length=15)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso / Crédito'), ('egreso', 'Egreso / Débito')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tesoreria.cuentabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejecutada', models.BooleanField(default=False)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='tesoreria.cuentabancaria')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='tesoreria.cuentabancaria')),
            ],
        ),
    ]
