# Generated by Django 6.0.3 on 2026-04-21 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='codigo_swift',
        ),
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='transferenciabancaria',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='transferenciabancaria',
            name='origen',
        ),
        migrations.AddField(
            model_name='banco',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='pais',
            field=models.CharField(default='Ecuador', max_length=50),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_asignado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='titular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='cliente_nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='cliente_ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='concepto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='concepto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor_nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor_ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='concepto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferenciabancaria',
            name='cuenta_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='tesoreria.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='transferenciabancaria',
            name='cuenta_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='tesoreria.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='transferenciabancaria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciabancaria',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transferenciabancaria',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.cuentabancaria')),
                ('cxc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='tesoreria.cuentaporcobrar')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tesoreria.caja')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.cuentabancaria')),
                ('cxp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tesoreria.cuentaporpagar')),
            ],
        ),
    ]
