# Generated by Django 6.0.3 on 2026-04-21 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('rendimiento', models.DecimalField(decimal_places=2, help_text='Cantidad que produce esta fórmula', max_digits=12)),
                ('unidad_rendimiento', models.CharField(default='Lote', max_length=20)),
                ('costo_materia_prima', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('instrucciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('obsoleta', 'Obsoleta')], default='borrador', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='kg', max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proveedor_ref', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.categoriamateriaprima')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('es_critica', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='produccion.formula')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_planificada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='planificada', max_length=15)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.formula')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, null=True, unique=True)),
                ('fecha_produccion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('produccion', 'En Producción'), ('control', 'Control de Calidad'), ('aprobado', 'Aprobado'), ('liberado', 'Liberado'), ('rechazado', 'Rechazado')], default='produccion', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_estimado', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.categoriaproductoterminado')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='produccion.productoterminado'),
        ),
    ]
