# Generated by Django 6.0.3 on 2026-04-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('glosa', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('anulado', 'Anulado')], default='borrador', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones Contables',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('naturaleza', models.CharField(choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], max_length=10)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('costo', 'Costo'), ('egreso', 'Gasto')], max_length=15)),
                ('es_detalle', models.BooleanField(default=True, help_text='Permite registrar asientos')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
