# Generated by Django 6.0.3 on 2026-04-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
    ]
