# Generated by Django 6.0.3 on 2026-04-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_categoriaproductocompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='impuesto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
