# Generated by Django 6.0.3 on 2026-04-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_ordencompra_fecha_entrega_ordencompra_impuesto_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_aceptada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordencompra')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.recepcioncompra')),
            ],
        ),
    ]
