# Generated by Django 6.0.3 on 2026-04-21 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('meta_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='vendedores.vendedor')),
            ],
        ),
    ]
